name: Tessera Docker Push

on:
  push:
    branches:
      - master
    tags:
      - tessera-*

jobs:
  push-latest:
    name: Push latest
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_REPO }}
          tags: latest
          add_git_labels: true
  push-tag:
    name: Push tag
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/tessera-')
    steps:
      - uses: actions/checkout@v2
      - name: Determine tag name
        id: tag
        shell: bash
        run: |
          REF=${{ github.ref }}
          PREFIX="refs\/tags\/tessera-"
          TAG=$(echo "$REF" | sed "s/^$PREFIX//")
          echo "::set-output name=name::$TAG"
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_REPO }}
          tags: ${{ steps.tag.outputs.name }}
          add_git_labels: true
